name: battle_simulation
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.6
  flutter_riverpod: ^3.1.0
  hive_ce: ^2.19.1
  provider: ^6.1.5+1
  riverpod: ^3.1.0
  path_provider: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:  
    - lib/assets/backgrounds/
    - lib/assets/fonts/
    - lib/assets/icon/
    - lib/assets/images/
    - lib/assets/characters/
    - lib/assets/monster/green/idle/
    - lib/assets/monster/orange/idle/
    - lib/assets/monster/blue/idle/
    - lib/assets/monster/blue/hit/
    - lib/assets/monster/green/hit/
    - lib/assets/monster/orange/hit/
    

  fonts:
  - family: Berry
    fonts:
      - asset: lib/assets/fonts/BerryRotunda.ttf


flutter_native_splash:
  color: "#000000"
  image: lib/assets/icon/splash_screen.png

  